# Reusable workflow for releases; to eject, you can replace this file with
# https://github.com/ryansonshine/ryansonshine/blob/main/.github/workflows/release.yml
name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: ryansonshine/ryansonshine/.github/workflows/release.yml@main
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
